version: "3.9"
services:
  grpc-server:
    image: node
    volumes:
      - ..:/workspace

  grpc-web-proxy:
    build: .
    ports:
      - 9090:9090

  mongodb:
    image : mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongodb