version: '3.9'
services:
  grpc-server:
    image: golang
    container_name: grpc-server
    volumes:
      - ..:/workspace

  grpc-web-proxy:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - grpc-server
  
  envoy:
    image: envoyproxy/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
      - "9090:9090"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: unless-stopped