version: '3.9'
services:
  grpc-server:
    image: ghcr.io/snoozehub/snoozehub-backend
    container_name: grpc-server
    volumes:
      - ./secrets:/app/secrets
    depends_on:
      - mongodb

  grpc-web-proxy:
    build: 
      dockerfile: proxy.Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - grpc-server

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root