version: '3.9'
services:
  grpc-server:
    build:
      context: ..
    container_name: grpc-server
    volumes:
      - ./secrets:/app/secrets
    networks:
      - proxynet
    depends_on:
      - mongodb

  mongodb:
    image : mongo
    container_name: mongodb
    networks:
      - proxynet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    mongodb:

networks:
  proxynet:
    external: 
      name: custom_network