version: '3.9'
services:
  grpc-server:
    build:
      context: ..
    volumes:
      - ./secrets:/app/secrets 
    depends_on:
      - mongodb

  mongodb:
    image : mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks:
  proxynet:
    name: custom_network