// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: common-messages.proto

package grpc_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feature int32

const (
	Feature_internetConnection Feature = 0
	Feature_bathroom           Feature = 1
	Feature_heating            Feature = 2
	Feature_airConditioner     Feature = 3
	Feature_electricalOutlet   Feature = 4
	Feature_tap                Feature = 5
	Feature_bedLinens          Feature = 6
	Feature_pillows            Feature = 7
)

// Enum value maps for Feature.
var (
	Feature_name = map[int32]string{
		0: "internetConnection",
		1: "bathroom",
		2: "heating",
		3: "airConditioner",
		4: "electricalOutlet",
		5: "tap",
		6: "bedLinens",
		7: "pillows",
	}
	Feature_value = map[string]int32{
		"internetConnection": 0,
		"bathroom":           1,
		"heating":            2,
		"airConditioner":     3,
		"electricalOutlet":   4,
		"tap":                5,
		"bedLinens":          6,
		"pillows":            7,
	}
)

func (x Feature) Enum() *Feature {
	p := new(Feature)
	*p = x
	return p
}

func (x Feature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Feature) Descriptor() protoreflect.EnumDescriptor {
	return file_common_messages_proto_enumTypes[0].Descriptor()
}

func (Feature) Type() protoreflect.EnumType {
	return &file_common_messages_proto_enumTypes[0]
}

func (x Feature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Feature.Descriptor instead.
func (Feature) EnumDescriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{0}
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // length=1-40
	Surname          string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`                   // length=1-40
	Mail             string `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`                         // Is a valid mail format, max length=60
	TelegramUsername string `protobuf:"bytes,4,opt,name=telegramUsername,proto3" json:"telegramUsername,omitempty"` // Valid format, without '@'
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountInfo) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *AccountInfo) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *AccountInfo) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

type ProfilePic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3,oneof" json:"image,omitempty"` // Valid AVIF image, max size = 512kb
}

func (x *ProfilePic) Reset() {
	*x = ProfilePic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilePic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePic) ProtoMessage() {}

func (x *ProfilePic) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePic.ProtoReflect.Descriptor instead.
func (*ProfilePic) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ProfilePic) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Booking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId *BedId `protobuf:"bytes,1,opt,name=bedId,proto3" json:"bedId,omitempty"`
	Date  *Date  `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // Refers to the night between the date and the next day
}

func (x *Booking) Reset() {
	*x = Booking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Booking) GetBedId() *BedId {
	if x != nil {
		return x.BedId
	}
	return nil
}

func (x *Booking) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

type BedMutableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address           string       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // length=1-100. Maximum sensitive (aka it search the exact string)
	Coordinates       *Coordinates `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Images            [][]byte     `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`                          // Valid 1-5 AVIF images, max size = 512kb
	Description       string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                // length=0-200
	Features          []Feature    `protobuf:"varint,5,rep,packed,name=features,proto3,enum=Feature" json:"features,omitempty"` // Distinct
	MinimumDaysNotice uint32       `protobuf:"varint,6,opt,name=minimumDaysNotice,proto3" json:"minimumDaysNotice,omitempty"`   //  min = 1, max = 30
}

func (x *BedMutableInfo) Reset() {
	*x = BedMutableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedMutableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedMutableInfo) ProtoMessage() {}

func (x *BedMutableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedMutableInfo.ProtoReflect.Descriptor instead.
func (*BedMutableInfo) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{4}
}

func (x *BedMutableInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BedMutableInfo) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *BedMutableInfo) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BedMutableInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BedMutableInfo) GetFeatures() []Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *BedMutableInfo) GetMinimumDaysNotice() uint32 {
	if x != nil {
		return x.MinimumDaysNotice
	}
	return 0
}

type BedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beds []*BedList_Bed `protobuf:"bytes,1,rep,name=beds,proto3" json:"beds,omitempty"`
}

func (x *BedList) Reset() {
	*x = BedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedList) ProtoMessage() {}

func (x *BedList) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedList.ProtoReflect.Descriptor instead.
func (*BedList) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BedList) GetBeds() []*BedList_Bed {
	if x != nil {
		return x.Beds
	}
	return nil
}

type BedId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId string `protobuf:"bytes,1,opt,name=bedId,proto3" json:"bedId,omitempty"` // Not empty. Is valid (exist)
}

func (x *BedId) Reset() {
	*x = BedId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedId) ProtoMessage() {}

func (x *BedId) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedId.ProtoReflect.Descriptor instead.
func (*BedId) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BedId) GetBedId() string {
	if x != nil {
		return x.BedId
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evaluation uint32 `protobuf:"varint,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"` // min = 0, max = 50. For example 42 is evaluated as 4.2
	Comment    string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`        // length=0-200
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Review) GetEvaluation() uint32 {
	if x != nil {
		return x.Evaluation
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   uint32 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month uint32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year  uint32 `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Date) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Date) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   // range: [-90, 90]
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` // range: [-180, 180]
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type BedList_Bed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                *BedId          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BedMutableInfo    *BedMutableInfo `protobuf:"bytes,2,opt,name=bedMutableInfo,proto3" json:"bedMutableInfo,omitempty"`
	DateAvailables    []*Date         `protobuf:"bytes,3,rep,name=dateAvailables,proto3" json:"dateAvailables,omitempty"` //0-90 .  Refers to the night between the date and the next day. It's valid. Every date is > today
	ReviewCount       uint32          `protobuf:"varint,4,opt,name=reviewCount,proto3" json:"reviewCount,omitempty"`
	AverageEvaluation *uint32         `protobuf:"varint,5,opt,name=averageEvaluation,proto3,oneof" json:"averageEvaluation,omitempty"` // min = 0, max = 50. For example 42 is evaluated as 4.2. Not set if and only if reviewCount is 0
}

func (x *BedList_Bed) Reset() {
	*x = BedList_Bed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedList_Bed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedList_Bed) ProtoMessage() {}

func (x *BedList_Bed) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedList_Bed.ProtoReflect.Descriptor instead.
func (*BedList_Bed) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{5, 0}
}

func (x *BedList_Bed) GetId() *BedId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BedList_Bed) GetBedMutableInfo() *BedMutableInfo {
	if x != nil {
		return x.BedMutableInfo
	}
	return nil
}

func (x *BedList_Bed) GetDateAvailables() []*Date {
	if x != nil {
		return x.DateAvailables
	}
	return nil
}

func (x *BedList_Bed) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *BedList_Bed) GetAverageEvaluation() uint32 {
	if x != nil && x.AverageEvaluation != nil {
		return *x.AverageEvaluation
	}
	return 0
}

var File_common_messages_proto protoreflect.FileDescriptor

var file_common_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x7b, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6c,
	0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a,
	0x0a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x19, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x22, 0x42, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x05, 0x62,
	0x65, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x42, 0x65, 0x64,
	0x49, 0x64, 0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x22, 0xe8, 0x01, 0x0a, 0x0e, 0x42, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x08, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x44, 0x61, 0x79, 0x73,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x6d, 0x69,
	0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x44, 0x61, 0x79, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x22,
	0x9e, 0x02, 0x0a, 0x07, 0x42, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x62,
	0x65, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x65, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x2e, 0x42, 0x65, 0x64, 0x52, 0x04, 0x62, 0x65, 0x64, 0x73, 0x1a, 0xf0, 0x01,
	0x0a, 0x03, 0x42, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x42, 0x65, 0x64, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a,
	0x0e, 0x62, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x62, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x11, 0x61, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x11, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x61,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x1d, 0x0a, 0x05, 0x42, 0x65, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x64,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x22,
	0x42, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x2a, 0x8b, 0x01, 0x0a, 0x07, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x12,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x68, 0x72, 0x6f, 0x6f, 0x6d,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12,
	0x12, 0x0a, 0x0e, 0x61, 0x69, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x61,
	0x6c, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x74, 0x61, 0x70,
	0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x62, 0x65, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x6e, 0x73, 0x10,
	0x06, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x69, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x10, 0x07, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_messages_proto_rawDescOnce sync.Once
	file_common_messages_proto_rawDescData = file_common_messages_proto_rawDesc
)

func file_common_messages_proto_rawDescGZIP() []byte {
	file_common_messages_proto_rawDescOnce.Do(func() {
		file_common_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_messages_proto_rawDescData)
	})
	return file_common_messages_proto_rawDescData
}

var file_common_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_messages_proto_goTypes = []interface{}{
	(Feature)(0),           // 0: Feature
	(*Empty)(nil),          // 1: Empty
	(*AccountInfo)(nil),    // 2: AccountInfo
	(*ProfilePic)(nil),     // 3: ProfilePic
	(*Booking)(nil),        // 4: Booking
	(*BedMutableInfo)(nil), // 5: BedMutableInfo
	(*BedList)(nil),        // 6: BedList
	(*BedId)(nil),          // 7: BedId
	(*Review)(nil),         // 8: Review
	(*Date)(nil),           // 9: Date
	(*Coordinates)(nil),    // 10: Coordinates
	(*BedList_Bed)(nil),    // 11: BedList.Bed
}
var file_common_messages_proto_depIdxs = []int32{
	7,  // 0: Booking.bedId:type_name -> BedId
	9,  // 1: Booking.date:type_name -> Date
	10, // 2: BedMutableInfo.coordinates:type_name -> Coordinates
	0,  // 3: BedMutableInfo.features:type_name -> Feature
	11, // 4: BedList.beds:type_name -> BedList.Bed
	7,  // 5: BedList.Bed.id:type_name -> BedId
	5,  // 6: BedList.Bed.bedMutableInfo:type_name -> BedMutableInfo
	9,  // 7: BedList.Bed.dateAvailables:type_name -> Date
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_common_messages_proto_init() }
func file_common_messages_proto_init() {
	if File_common_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilePic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Booking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedMutableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedList_Bed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_messages_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_common_messages_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_messages_proto_goTypes,
		DependencyIndexes: file_common_messages_proto_depIdxs,
		EnumInfos:         file_common_messages_proto_enumTypes,
		MessageInfos:      file_common_messages_proto_msgTypes,
	}.Build()
	File_common_messages_proto = out.File
	file_common_messages_proto_rawDesc = nil
	file_common_messages_proto_goTypes = nil
	file_common_messages_proto_depIdxs = nil
}
