// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: common-messages.proto

package grpc_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{0}
}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // length=1-40
	Surname          string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`                   // length=1-40
	Mail             string `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`                         // Is a valid mail format, max length=60
	TelegramUsername string `protobuf:"bytes,4,opt,name=telegramUsername,proto3" json:"telegramUsername,omitempty"` // Valid format, without '@'
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountInfo) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *AccountInfo) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *AccountInfo) GetTelegramUsername() string {
	if x != nil {
		return x.TelegramUsername
	}
	return ""
}

type ProfilePic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3,oneof" json:"image,omitempty"` // Valid AVIF image, max size = 512kb
}

func (x *ProfilePic) Reset() {
	*x = ProfilePic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilePic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePic) ProtoMessage() {}

func (x *ProfilePic) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePic.ProtoReflect.Descriptor instead.
func (*ProfilePic) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ProfilePic) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Features struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternetConnection bool `protobuf:"varint,1,opt,name=internetConnection,proto3" json:"internetConnection,omitempty"`
	Bathroom           bool `protobuf:"varint,2,opt,name=bathroom,proto3" json:"bathroom,omitempty"`
	Heating            bool `protobuf:"varint,3,opt,name=heating,proto3" json:"heating,omitempty"`
	AirConditioner     bool `protobuf:"varint,4,opt,name=airConditioner,proto3" json:"airConditioner,omitempty"`
	ElectricalOutlet   bool `protobuf:"varint,5,opt,name=electricalOutlet,proto3" json:"electricalOutlet,omitempty"`
	Tap                bool `protobuf:"varint,6,opt,name=tap,proto3" json:"tap,omitempty"`
	BedLinens          bool `protobuf:"varint,7,opt,name=bedLinens,proto3" json:"bedLinens,omitempty"`
	Pillows            bool `protobuf:"varint,8,opt,name=pillows,proto3" json:"pillows,omitempty"`
}

func (x *Features) Reset() {
	*x = Features{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Features) GetInternetConnection() bool {
	if x != nil {
		return x.InternetConnection
	}
	return false
}

func (x *Features) GetBathroom() bool {
	if x != nil {
		return x.Bathroom
	}
	return false
}

func (x *Features) GetHeating() bool {
	if x != nil {
		return x.Heating
	}
	return false
}

func (x *Features) GetAirConditioner() bool {
	if x != nil {
		return x.AirConditioner
	}
	return false
}

func (x *Features) GetElectricalOutlet() bool {
	if x != nil {
		return x.ElectricalOutlet
	}
	return false
}

func (x *Features) GetTap() bool {
	if x != nil {
		return x.Tap
	}
	return false
}

func (x *Features) GetBedLinens() bool {
	if x != nil {
		return x.BedLinens
	}
	return false
}

func (x *Features) GetPillows() bool {
	if x != nil {
		return x.Pillows
	}
	return false
}

type Booking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId *BedId `protobuf:"bytes,1,opt,name=bedId,proto3" json:"bedId,omitempty"`
	Date  uint32 `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"` // Refers to the night between the date and the next day, 8 digit (base 10) number, for example 30012000 -> 30-01-2000.
}

func (x *Booking) Reset() {
	*x = Booking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Booking) GetBedId() *BedId {
	if x != nil {
		return x.BedId
	}
	return nil
}

func (x *Booking) GetDate() uint32 {
	if x != nil {
		return x.Date
	}
	return 0
}

type BedMutableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place             string    `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`                   // length=1-100
	Images            [][]byte  `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`                 // Valid 1-5 AVIF images, max size = 512kb
	Description       *string   `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"` // Not empty (trimmed)
	Features          *Features `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	MinimumDaysNotice uint32    `protobuf:"varint,4,opt,name=minimumDaysNotice,proto3" json:"minimumDaysNotice,omitempty"` //  min = 1, max = 30
}

func (x *BedMutableInfo) Reset() {
	*x = BedMutableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedMutableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedMutableInfo) ProtoMessage() {}

func (x *BedMutableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedMutableInfo.ProtoReflect.Descriptor instead.
func (*BedMutableInfo) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{5}
}

func (x *BedMutableInfo) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *BedMutableInfo) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BedMutableInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BedMutableInfo) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *BedMutableInfo) GetMinimumDaysNotice() uint32 {
	if x != nil {
		return x.MinimumDaysNotice
	}
	return 0
}

type BedList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beds []*BedList_Bed `protobuf:"bytes,1,rep,name=beds,proto3" json:"beds,omitempty"`
}

func (x *BedList) Reset() {
	*x = BedList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedList) ProtoMessage() {}

func (x *BedList) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedList.ProtoReflect.Descriptor instead.
func (*BedList) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{6}
}

func (x *BedList) GetBeds() []*BedList_Bed {
	if x != nil {
		return x.Beds
	}
	return nil
}

type BedId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId string `protobuf:"bytes,1,opt,name=bedId,proto3" json:"bedId,omitempty"` // Not empty. Is valid (exist)
}

func (x *BedId) Reset() {
	*x = BedId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedId) ProtoMessage() {}

func (x *BedId) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedId.ProtoReflect.Descriptor instead.
func (*BedId) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BedId) GetBedId() string {
	if x != nil {
		return x.BedId
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evaluation uint32  `protobuf:"varint,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"` // min = 0, max = 50. For example 42 is evaluated as 4.2
	Comment    *string `protobuf:"bytes,2,opt,name=comment,proto3,oneof" json:"comment,omitempty"`  // length=1-200
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Review) GetEvaluation() uint32 {
	if x != nil {
		return x.Evaluation
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type BedList_Bed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                *BedId          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BedMutableInfo    *BedMutableInfo `protobuf:"bytes,2,opt,name=bedMutableInfo,proto3,oneof" json:"bedMutableInfo,omitempty"`
	DateAvailables    []uint32        `protobuf:"varint,3,rep,packed,name=dateAvailables,proto3" json:"dateAvailables,omitempty"` //0-90 .  Refers to the night between the date and the next day, 8 digit (base 10) number, for example 30012000 -> 30-01-2000. It's valid
	ReviewCount       uint32          `protobuf:"varint,4,opt,name=reviewCount,proto3" json:"reviewCount,omitempty"`
	AverageEvaluation *uint32         `protobuf:"varint,5,opt,name=averageEvaluation,proto3,oneof" json:"averageEvaluation,omitempty"` // min = 0, max = 50. For example 42 is evaluated as 4.2. Not set if and only if reviewCount is 0
}

func (x *BedList_Bed) Reset() {
	*x = BedList_Bed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BedList_Bed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedList_Bed) ProtoMessage() {}

func (x *BedList_Bed) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedList_Bed.ProtoReflect.Descriptor instead.
func (*BedList_Bed) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{6, 0}
}

func (x *BedList_Bed) GetId() *BedId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BedList_Bed) GetBedMutableInfo() *BedMutableInfo {
	if x != nil {
		return x.BedMutableInfo
	}
	return nil
}

func (x *BedList_Bed) GetDateAvailables() []uint32 {
	if x != nil {
		return x.DateAvailables
	}
	return nil
}

func (x *BedList_Bed) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *BedList_Bed) GetAverageEvaluation() uint32 {
	if x != nil && x.AverageEvaluation != nil {
		return *x.AverageEvaluation
	}
	return 0
}

var File_common_messages_proto protoreflect.FileDescriptor

var file_common_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x7b, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x65, 0x6c,
	0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a,
	0x0a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x19, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x22, 0x8e, 0x02, 0x0a, 0x08, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x2e, 0x0a,
	0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x62, 0x61, 0x74, 0x68, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x62, 0x61, 0x74, 0x68, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x65, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x69, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x61, 0x69, 0x72,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x61,
	0x6c, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x61, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x64,
	0x4c, 0x69, 0x6e, 0x65, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x65,
	0x64, 0x4c, 0x69, 0x6e, 0x65, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x6c, 0x6c, 0x6f,
	0x77, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x69, 0x6c, 0x6c, 0x6f, 0x77,
	0x73, 0x22, 0x3b, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x05,
	0x62, 0x65, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x42, 0x65,
	0x64, 0x49, 0x64, 0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0xca,
	0x01, 0x0a, 0x0e, 0x42, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x2c, 0x0a,
	0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x44, 0x61, 0x79, 0x73, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75,
	0x6d, 0x44, 0x61, 0x79, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xaf, 0x02, 0x0a, 0x07,
	0x42, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x65, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x42, 0x65, 0x64, 0x52, 0x04, 0x62, 0x65, 0x64, 0x73, 0x1a, 0x81, 0x02, 0x0a, 0x03, 0x42, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x42, 0x65, 0x64, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x0e, 0x62, 0x65, 0x64,
	0x4d, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x62, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0e, 0x64, 0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x31, 0x0a, 0x11, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x11,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x62, 0x65, 0x64, 0x4d, 0x75, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x61, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1d, 0x0a,
	0x05, 0x42, 0x65, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x06,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_messages_proto_rawDescOnce sync.Once
	file_common_messages_proto_rawDescData = file_common_messages_proto_rawDesc
)

func file_common_messages_proto_rawDescGZIP() []byte {
	file_common_messages_proto_rawDescOnce.Do(func() {
		file_common_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_messages_proto_rawDescData)
	})
	return file_common_messages_proto_rawDescData
}

var file_common_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_messages_proto_goTypes = []interface{}{
	(*Empty)(nil),          // 0: Empty
	(*AccountInfo)(nil),    // 1: AccountInfo
	(*ProfilePic)(nil),     // 2: ProfilePic
	(*Features)(nil),       // 3: Features
	(*Booking)(nil),        // 4: Booking
	(*BedMutableInfo)(nil), // 5: BedMutableInfo
	(*BedList)(nil),        // 6: BedList
	(*BedId)(nil),          // 7: BedId
	(*Review)(nil),         // 8: Review
	(*BedList_Bed)(nil),    // 9: BedList.Bed
}
var file_common_messages_proto_depIdxs = []int32{
	7, // 0: Booking.bedId:type_name -> BedId
	3, // 1: BedMutableInfo.features:type_name -> Features
	9, // 2: BedList.beds:type_name -> BedList.Bed
	7, // 3: BedList.Bed.id:type_name -> BedId
	5, // 4: BedList.Bed.bedMutableInfo:type_name -> BedMutableInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_messages_proto_init() }
func file_common_messages_proto_init() {
	if File_common_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilePic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Booking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedMutableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BedList_Bed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_messages_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_common_messages_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_common_messages_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_common_messages_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_messages_proto_goTypes,
		DependencyIndexes: file_common_messages_proto_depIdxs,
		MessageInfos:      file_common_messages_proto_msgTypes,
	}.Build()
	File_common_messages_proto = out.File
	file_common_messages_proto_rawDesc = nil
	file_common_messages_proto_goTypes = nil
	file_common_messages_proto_depIdxs = nil
}
